### ISSUE TITLE
To-Do

### ISSUE THREAD

**Issue by azerupi** [azerupi/mdBook#1]
# Overview of things to do

## Build

Part that builds the book from the markdown files

- [x] data structure for book --> BookItem
- [ ] parse `SUMMARY.md` #2 *(Rudimentary implementation done)*
- [x] Create toc
- [x] markdown support
- [ ] Multilingual support
- [ ] 

## Renderer

See issue #3 

- [ ] html renderer (using handlebars)

## Theme

Html, Css and JavaScript files that will be used to render the website.

See issue #4 

- [x] basic default theme
    - [x] basic html
    - [x] basic css
    - [x] basic js
- [x] use [Handlebars](https://github.com/sunng87/handlebars-rust) for templating ?
- [ ] possible to have custom theme by adding a `theme` directory in `src`
    - [ ] only selectively overwrite files of the theme

## Config

- [x] create a `BookConfig` struct to store config parameters
- [ ] `.book` config file
- [ ] add function `read_config`  (builder pattern)

### mdbook init

Command to create boilerplate files and directory structure

- [x] If it does not exist, create `src` folder
- [x] If it does not exist, create `book` folder (output)
- [x] If it does not exist, create `src/SUMMARY.md` with 1 example chapter
- [x] Create the example chapter file `src/chapter_1.md`
- [x] `mdbook init [path]` init the given directory by path instead of the current directory
- [ ] add a flag that creates the `src/theme` directory with the default theme for modification
- [ ] When `SUMARRY.md` exist, parse it and create the chapter files of they do not exist.

### mdbook build

- [x] `mdbook build [path]` builds the given directory by path instead of the current directory

### mdbook watch

Command to watch the files and trigger a build when some files changed

- [ ] trigger build on file change
